In [1]:
import tensorcircuit as tc
import numpy as np

2022-07-26 12:10:50.090052: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-07-26 12:10:50.090070: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
def oracle1(c):
#    print(c.state())
    for i in range(1,6): c.CNOT(0,i)
    c.multicontrol(1,2,3,4,5,6,ctrl=[1,0,1,0,1],unitary=tc.gates.x())
    c.z(6)
    c.multicontrol(1,2,3,4,5,6,ctrl=[1,0,1,0,1],unitary=tc.gates.x())
    for i in range(1,6): c.CNOT(0,i)
#    print(c.state())

In [3]:
def reflection(n,c):
    for i in range(n):
        c.H(i)
        c.X(i)
    c.multicontrol(*range(n), unitary=tc.gates.z(), ctrl=[1 for _ in range(n - 1)])
    for i in range(n):
        c.X(i)
        c.H(i)
    return c

In [6]:
def grover(n,m,oracle,solution_amount):
    def grover_unit(n,m,oracle):
        c=tc.Circuit(n+m)
        for i in range(n):
            c.H(i)
        theta=np.arcsin(np.sqrt(solution_amount/2**n))*2
        phi=theta/2
        while phi+theta<np.pi/2:
            phi+=theta
            oracle(c)
            reflection(n,c)
        return c.measure(*range(n), with_prob = True)
    for i in range(5):
        print(grover_unit(n,m,oracle))
        
grover(6,1,oracle1,2)

(array([0., 1., 0., 1., 0., 1.], dtype=float32), 0.4484671558979498)
(array([1., 0., 1., 0., 1., 0.], dtype=float32), 0.44846716421562816)
(array([1., 0., 1., 0., 1., 0.], dtype=float32), 0.4484671829639982)
(array([0., 1., 0., 1., 0., 1.], dtype=float32), 0.448467138960721)
(array([1., 0., 1., 0., 1., 0.], dtype=float32), 0.448467089810496)
