In [2]:
import tensorcircuit as tc
import numpy as np
from scipy.linalg import expm, sinm, cosm
n=int(input())
H = np.zeros((2**n, 2**n))
for i in range(n):
    H += np.kron(np.kron(np.identity(2**i),tc.gates._z_matrix),np.identity(2**(n-i-1)))
for i in range(n-1):
    H += np.kron(np.kron(np.identity(2**i),tc.gates._x_matrix),np.identity(2**(n-i-1)))*np.kron(np.kron(np.identity(2**(i+1)),tc.gates._x_matrix),np.identity(2**(n-i-2)))
print(H)
print(H[0,0])

3
[[ 3.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -3.]]
3.0
